'use client';
import { useEffect, useMemo, useState } from 'react';
import { marked } from 'marked';
import { fetchNotebook, artifactUrl } from '@/lib/api';
import type { Notebook, NotebookCell } from '@/lib/types';

marked.setOptions({ gfm: true, breaks: false });

function cellSource(cell: NotebookCell): string {
  return Array.isArray(cell.source) ? cell.source.join('') : cell.source;
}

/** Very small Python syntax highlighter — keywords, strings, comments, numbers. */
function highlightPython(code: string): string {
  const escaped = code
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  return escaped
    // comments first (so keywords inside don't match)
    .replace(/(#[^\n]*)/g, '<span class="tok-comment">$1</span>')
    // triple + single/double strings
    .replace(/("""[\s\S]*?"""|'''[\s\S]*?'''|"[^"\n]*"|'[^'\n]*')/g, '<span class="tok-string">$1</span>')
    // keywords
    .replace(
      /\b(import|from|as|def|class|return|if|elif|else|for|while|in|not|and|or|try|except|finally|with|lambda|None|True|False|raise|pass|continue|break|global|yield|assert|del|is)\b/g,
      '<span class="tok-keyword">$1</span>'
    )
    // numbers
    .replace(/\b(\d+\.?\d*)\b/g, '<span class="tok-number">$1</span>');
}

function CodeCell({ source, index }: { source: string; index: number }) {
  const [copied, setCopied] = useState(false);
  const highlighted = useMemo(() => highlightPython(source), [source]);

  const copy = () => {
    navigator.clipboard.writeText(source).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };

  return (
    <div className="group relative my-3 rounded-xl overflow-hidden border border-bone/10 bg-obsidian-900">
      {/* Cell gutter header */}
      <div className="flex items-center justify-between px-4 py-2 bg-obsidian-900/70 border-b border-bone/10">
        <span className="text-[11px] font-mono text-gold-500">In [{index}]</span>
        <button
          onClick={copy}
          className="text-[11px] text-bone-faint hover:text-bone-dim opacity-0 group-hover:opacity-100 transition-opacity"
        >
          {copied ? '✓ Copied' : 'Copy'}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto text-[12.5px] leading-relaxed font-mono text-bone-dim">
        <code dangerouslySetInnerHTML={{ __html: highlighted }} />
      </pre>
    </div>
  );
}

function MarkdownCell({ source }: { source: string }) {
  const html = useMemo(() => marked.parse(source) as string, [source]);
  return (
    <div
      className="nb-markdown py-2"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export default function NotebookViewer({ runId }: { runId: string }) {
  const [notebook, setNotebook] = useState<Notebook | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchNotebook(runId)
      .then(setNotebook)
      .catch((e) => setError(e instanceof Error ? e.message : 'Failed to load notebook'))
      .finally(() => setLoading(false));
  }, [runId]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-48 gap-3">
        <div className="w-8 h-8 rounded-full border-2 border-gold-500 border-t-transparent animate-spin" />
        <p className="text-xs text-bone-faint">Loading evidence notebook…</p>
      </div>
    );
  }

  if (error || !notebook) {
    return (
      <div className="flex flex-col items-center justify-center h-48 gap-2 text-bone-faint">
        <div className="text-3xl">📓</div>
        <p className="text-sm">{error ?? 'Notebook not available'}</p>
        <p className="text-xs text-bone-ghost">It is generated by the Exporter agent when a run completes.</p>
      </div>
    );
  }

  let codeIndex = 0;

  return (
    <div>
      {/* Toolbar */}
      <div className="flex items-center justify-between mb-4 pb-3 border-b border-bone/10">
        <div className="flex items-center gap-2">
          <span className="text-lg">📓</span>
          <div>
            <p className="text-sm font-medium text-bone">pipeline.ipynb</p>
            <p className="text-[11px] text-bone-faint">
              {notebook.cells.length} cells · LLM-narrated · actual executed code
            </p>
          </div>
        </div>
        <a
          href={artifactUrl(runId, 'notebook')}
          download="pipeline.ipynb"
          className="text-xs text-gold-400 hover:text-gold-300 border border-gold-700/60 hover:border-gold-600 rounded-lg px-3 py-1.5 transition-all hover:shadow-[0_0_12px_rgba(200,169,110,0.3)]"
        >
          ⬇ Download .ipynb
        </a>
      </div>

      {/* Cells */}
      <div className="max-h-[640px] overflow-y-auto pr-2 nb-scroll">
        {notebook.cells.map((cell, i) => {
          const src = cellSource(cell);
          if (cell.cell_type === 'code') {
            codeIndex += 1;
            return <CodeCell key={i} source={src} index={codeIndex} />;
          }
          return <MarkdownCell key={i} source={src} />;
        })}
      </div>
    </div>
  );
}
