"""baseline — current schema as of Phase 0.4 (Alembic adoption)

This is a no-op marker revision. The existing schema was created by
``Base.metadata.create_all`` (and a few hand-run ALTER TABLEs). We adopt Alembic
WITHOUT rewriting that history: stamp existing databases at this revision, then
manage every future change with ``alembic revision --autogenerate``.

Adoption steps (run once, per environment) — see docs/MIGRATIONS.md:
  existing DB:  alembic stamp 0001_baseline
  fresh DB:     create_all builds the tables, then  alembic stamp head

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-18
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Intentionally empty: the baseline schema already exists. Future schema
    # changes get their own autogenerated revisions on top of this one.
    pass


def downgrade() -> None:
    pass
